version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - AIR_USE_POLLING=true
      - AIR_POLLING_INTERVAL=1000
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: amb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306